### PR TITLE
Js refactor

### PR DESCRIPTION
**Pull request by mehulkar**
rebased PR from @jermspeaks. Thanks!

### CODE REVIEW

**Comment by jermspeaks** [comment]
Thanks @mehulkar

**Comment by mehulkar** [comment]
@jermspeaks thank you!

**Comment by mehulkar** [comment]
PS, I'll be online tonight around 8 to work on stuff if you want to tag team on things!

**Comment by jermspeaks** [comment]
Sure, I'll be online.

**Pull request merged**
