### PR TITLE
Store User Roles as Bitmask, Not Relation

### PR DESCRIPTION
**Pull request by nickbarnwell**

### CODE REVIEW

**Comment by nickbarnwell** [comment]
Barring objections from anyone who's worked with the Role code (@mehulkar ?) I'm going to run this against my test database in dev, make sure it doesn't horrificially break anything, then deploy this weekend.

**Comment by mehulkar** [comment]
Interesting. The point of this to make it easier to cache a users roles in the users table?

**Comment by nickbarnwell** [comment]
And simplify adding roles. They'll be defined in code, rather than the DB. We're not at the level where having dynamic role creation is terribly useful.

**Comment by mehulkar** [comment]
Speeds up queries too I guess. Does this completely remove the need for the roles table?

**Comment by nickbarnwell** [comment]
Yup. and makes them easier to write. No more joining on four different tables to figure out who should show up on a page!

I may have made this change primarily because I was too ~~dumb~~ lazy to figure out how to write some of the analytic queries I wanted

**Comment by mehulkar** [comment]
Yeah I've had that problem before. This is cool. Wish I had found this gem 6 months ago :)

**Comment by nickbarnwell** [comment]
The sad part is I wrote the code to do exactly what the gem does, then found out it existed and already had tests and was properly modularised :-1:… I was so excited to finally use my knowledge of bitwise operators

**Pull request merged**
