### PR TITLE
remove holiday indicator in css

### PR DESCRIPTION
**Pull request by clwrightwhen**
Hi @nickbarnwell,  I'm submitting this for your review regarding removing the holiday indicator from the stylesheet. 

Thanks, 

Cynthia

### CODE REVIEW

**Comment by mehulkar** [comment]
Is there a Github issue that's related to what this PR is meant to do? Looks like your fix is creating invalid css and I'm not sure what the intended fix was.

**Comment by clwrightwhen** [comment]
@mehulkar - see Slack update for reference. It was to remove CSS relating to the holiday indicator re: tea time availability over the holidays.

**Comment by clwrightwhen** [comment]
Red to yellow, really? It was missing a curly brace. Which I added.

**Comment by mehulkar** [comment]
I'm not sure this PR does what you want it to do. Those nested styles that you left will either interfere with other styles, or they are not necessary any more.

**Comment by clwrightwhen** [comment]
Hey @mehulkar - the styles I left are being referenced elsewhere within the app - which led me to think it is still needed in the .js and a file ending in .haml. I have not made any changes to these files -- since the Slack update *specifically* referenced changes needed in the CSS file.

**Comment by nickbarnwell** [comment]
@mehulkar, @clwrightwhen: [Here's the corresponding issue (Trello card)](https://trello.com/c/tpkdfd2l/55-turn-off-holiday-sparse-tea-time-indicator). 

The idea actually was to remove it completely, including the front-end code in `app/views/shared/_tea_times.html.haml` and `application.js`. Everything, including the nested styles that were children of the `#holidays-warning` specific styles, can be removed.

Sorry for not clarifying! Let me know if there's anything else that's unclear, and we should have this in and deployed by the weekend :+1: :)

**Comment by clwrightwhen** [comment]
it passed...

*falls out of chair* 

Travis is soo picky with the line spacing. 

@mehulkar and @nickbarnwell thank you for the feedback and clarification on this!

**Comment by nickbarnwell** [comment]
Hey @clwrightwhen, I went and fixed it up for you to save you the trouble, since it was such a tiny thing. Thanks a ton, and congratulations on making your first PR :tada:.

It wasn't so much the tests being picky about line spacing as it was HAML, which, like Python, is a whitespace sensitive language. While we're moving back to using pure `erb` (and then, once the redesign is complete and we start implementing front-end features in React, `JSX`), this [haml tutorial will get you up to speed](http://www.slideshare.net/mokolabs/haml-and-sass-in-15-minutes).

It's a great tool for prototyping - that's why we used it in the TWS v1 - but as you've seen here, it's a bit finicky and hard for beginners to quickly get up to speed on.

Let me know if you have any more qs here or in Slack. In the meantime, I'm going to merge and deploy this :fireworks:

**Comment by mehulkar** [comment]
@clwrightwhen gotcha. Thanks for explaining!
@nickbarnwell thanks for the link!

Good work team! 

/me pats self on back for not being useful at all i this PR.

**Pull request merged**
