### PR TITLE
Upgrade to Rails 4.2

### PR DESCRIPTION
**Pull request by nickbarnwell**
* Update delayed_job to Rails 4.2 compatible version
* Move to ActiveJob (where possible)
* Tests probably pass

### CODE REVIEW

**Comment by mmahalwy** [comment]
I think this is missing:
https://github.com/collectiveidea/delayed_job#rails-42

**Comment by mehulkar** [comment]
@nickbarnwell rebased this for you. let's get it merged and we can worry about moving to active job as a separate task/story.

**Comment by mehulkar** [comment]
(but we need travis to not be frozen). removing and readding the project should fix whatever happened. Or maybe enough things will timeout in a few hours that it will self-correct

**Comment by mehulkar** [comment]
@nickbarnwell this PR is going to be difficult to merge. especially with my bad upstream force push :( Luckily the only real parts of this are ++'ing the gem versions, so we can start cleanly from master.

**Pull request closed without merging**
