### PR TITLE
Making tea times more accessible via nav bar

### PR DESCRIPTION
**Pull request by ankitshah811**

### CODE REVIEW

**Comment by mehulkar** [comment]
this PR looks ok, but I don't have a good handle on what it's doing. Too many changes that are not related to the title of the PR. Pulled it down and nothing seems broken, so that's good enough for me.

**Comment by ankitshah811** [comment]
@mehulkar good point, this also adjusts the styles of the CTA to 'set home city' on dashboard and sets default styles for notifications on the site (similar to those used in the changes for #548). I didn't name this PR well

**Comment by ankitshah811** [comment]
@mehulkar is there a chance that the 5 PRs active right now are failing tests because https://github.com/TeaWithStrangers/tws-on-rails/commit/e652ab8abf4f7720482c3f474710053e6ac5de45 was failing?

**Comment by mehulkar** [comment]
this one didn't fail, it looks like was canceled before it completed (you can click on the red x and see details about what happened). Pretty sure I canceled it because I ran the test suite locally and it passed and the Travis queue was too long and I didn't want to wait.

**Pull request merged**
