### PR TITLE
fallback city style improvements

### PR DESCRIPTION
**Pull request by ankitshah811**

### CODE REVIEW

**Comment by ankitshah811** [comment]
Weird — didn't mean to make a PR with all of @nickbarnwell's commits as well. Did I do this one wrong?

**Comment by nickbarnwell** [comment]
The base branch is still set to forbes-launch not master. I can just fix it manually when I merge

**Comment by mehulkar** [comment]
@ankitshah811 yeah you want to make a PR against master, not forbes-launch.

**Comment by ankitshah811** [comment]
Oh! My bad. @nickbarnwell should I delete this and create a new PR?

**Pull request closed without merging**
