### PR TITLE
Feature/js refactor

### PR DESCRIPTION
**Pull request by jermspeaks**
Added a `.jshintrc` file and did some linting of the code.

### CODE REVIEW

**Comment by mehulkar** [comment]
Thanks @jermspeaks! Few kinda bikeshed/stylistic points:

- [ ] can you squash commits
- [ ] can you use 2 spaces instead of tabs / 4 spaces (not sure what you're using) (makes future diffs easier if we all use the same styles)

Also, since we don't have great tests for this, I'm assuming you've tested that the code still works as intended?

**Comment by jermspeaks** [comment]
Writing the tests still. I'm going to re-do that and re-submit a PR later tonight.

**Comment by mehulkar** [comment]
Oh ok. You can keep it open, no worries! Thanks again. :)

On Monday, June 1, 2015, Jeremy Wong <notifications@github.com> wrote:

> Closed #425 <https://github.com/TeaWithStrangers/tws-on-rails/pull/425>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeaWithStrangers/tws-on-rails/pull/425#event-319273449>
> .
>


-- 

------
Mehul Kar
@mehulkar

**Comment by mehulkar** [comment]
Closing in favor of #426

**Pull request closed without merging**
