### PR TITLE
Refactorjs

### PR DESCRIPTION
**Pull request by mehulkar**
courtesy of @jermspeaks

### CODE REVIEW

**Comment by mehulkar** [comment]
@jermspeaks can you verify this PR and also provide a provide a summary in a comment here of the purpose of this refactor? (i think you had it somewhere else, just a copy paste would be fine)

**Comment by jermspeaks** [comment]
- Reset `cities.js`
- Leave `Gemlock.lock` alone
- Sublime indentation to spaces
- Removed modal open for sign up (previously code was commented out)
- Initialized variables on top for performance
- Used function form for every file
- Refactored massive functions into smaller, manageable functions (for readability and clarity)
- Added comments to all functions
- Note: not entirely tested. Couldn't figure out how to do post-email button interactions in DEV environment. Tested everything else out in Chrome. Unsure about Firefox, Safari and IE.

**Comment by jermspeaks** [comment]
@mehulkar Verified. Thanks, I'll have to revert my fork.

**Comment by mehulkar** [comment]
> Used function form for every file
can you explain the purpose of this? (i'm not really a js person)

> Note: not entirely tested.

ok, i'll pull this down and test that the basic stuff works this week. Thanks!

**Comment by jermspeaks** [comment]
Function wrapping is common practice for various reasons. Primarily, I use it for name-spacing purposes, although really, it began because my JS Linter started complaining at me.

Resources:
- [StackOverflow](http://stackoverflow.com/questions/2421911/what-is-the-purpose-of-wrapping-whole-javascript-files-in-anonymous-functions-li) has a good write-up about it.
- [Strict Mode](http://yuiblog.com/blog/2010/12/14/strict-mode-is-coming-to-town/) purpose and function wrapping.

**Comment by mehulkar** [comment]
@jermspeaks this PR breaks things. The first thing I tested was the change to `application.js`. The `toggleHeader` function is supposed to show the navigation menu on mobile (or when the browser window is small and the hamburger menu is showing). With this patch applied, it looks like the styles are broken as well as the functionality (I see `Uncaught ReferenceError: toggleHeader is not defined` in console when I click the nav menu. 

Feel free to grab this branch off my fork (i'll leave it there for a while) and continue work on it and resubmit the PR when it is more ready. Closing this PR since you won't be able to push fixes to it anyway.

**Comment by jermspeaks** [comment]
Sure, thanks. I'll checkout the branch and fix the error.

**Pull request closed without merging**
