### PR TITLE
cities.js now sorts the cities it displays alphabetically

### PR DESCRIPTION
**Pull request by Calvyn82**
This is in response to Issue #297: Sort cities alphabetically.

https://github.com/TeaWithStrangers/tws-on-rails/issues/297

### CODE REVIEW

**Comment by ankitshah811** [comment]
Ah shit, @Calvyn82 thanks so much for doing this, but we should've closed this issue. The cities should be sorted by user count on `[/cities](http://teawithstrangers.com/cities)` (view: `_forbes_show.html.erb`). They should be sorted alphabetically on `[/cities/suggest](http://teawithstrangers.com/cities/suggest)`

The former is the case right now, but the latter is not. Can you revise this PR so that it applies your fix to /cities/suggest?

**Comment by ankitshah811** [comment]
btw, @Calvyn82, not sure if you've been looped in with the rest of the folks that are helping with dev on http://teawithstrangers.com/, but if you'd like to get more involved as a regular contributor and engage in our chat channels about dev priorities and approaches, email me (ankit at teawithstrangers.com) and I'll shoot you some info and access to our slack channels :)

**Comment by Calvyn82** [comment]
I'll make the fix. I just looked around until I found a list of cities. I should have asked on the issue comments before posting a pull request.

**Comment by ankitshah811** [comment]
No worries at all! You're awesome for jumping in to contribute man. Really appreciate you taking initiative :)

**Comment by mehulkar** [comment]
@Calvyn82 thanks for the PR! Going to close because it doesn't make sense to sort by name. I'll also close #297 until we figure out _how_ we want to organize the cities page. @ankitshah811 will be making that decision.

**Pull request closed without merging**
