### PR TITLE
Simple Metrics for Strainer

### PR DESCRIPTION
**Pull request by nickbarnwell**
This adds a simple statistics controller which exposes the following metrics on a JSON endpoint:

* Active Hosts by city in the last two weeks
* Host Count by City
* Total Tea Time Count by City

The next stage is to add parameters to them that allow you to filter by date range and enable them to be used to answer more specific questions, e.g:

* tea times in a city in a given period
* host count in a city on a month-by-month basis (not currently possible w. the way we are storing host data in the future, come to think of it)
* Active hosts during a given date range. E.g. so we can drill down into hosts who hosted each week in a month v. biweekly, v. just one week in a month

We should also add some similar metrics for attendances

@WilHall, want to look at how I modified the queries and make sure I didn't change what we were trying to measure?

### CODE REVIEW

**Comment by nickbarnwell** [comment]
I lied. If we want to do this without having to write new charting widgets for Dashing (which *I* don't particularly want to do), then the next step is to actually break this down so that all this info is returned as separate timeseries, probably sharded on city and then period. GG reading documentation

**Comment by mehulkar** [comment]
Why not serve raw data and do statistics as a separate beast?

**Comment by mehulkar** [comment]
On second look, I guess this is pretty raw. I guess I mean single resource endpoints.

**Comment by mehulkar** [comment]
not sure what the intention was, but we'll have to revisit this if we still want it. this is too much git for me to handle :/

**Comment by mehulkar** [comment]
pushed up to https://github.com/mehulkar/tws-on-rails/tree/statistics if we really want the code from here. i can't tell what the actual code in the PR original was.

**Pull request closed without merging**
