### PR TITLE
Fix city images so that they cover the div properly

### PR DESCRIPTION
**Pull request by rcchen**
Before:

image

After:

image

### CODE REVIEW

**Comment by rcchen** [comment]
Retriggering Travis

**Comment by nickbarnwell** [comment]
Thanks Roger!

**Comment by mehulkar** [comment]
Does this fix #292?

**Comment by nickbarnwell** [comment]
Yup



On Apr 19, 2015, at 12:38 PM, Mehul Kar <notifications@github.com> wrote:

Does this fix #292
<https://github.com/TeaWithStrangers/tws-on-rails/issues/292>?

—
Reply to this email directly or view it on GitHub
<https://github.com/TeaWithStrangers/tws-on-rails/pull/299#issuecomment-94307712>
.

**Comment by mehulkar** [comment]
Is this deployed?

**Comment by nickbarnwell** [comment]
Yes

**Comment by ankitshah811** [comment]
I love this! Thanks so much Roger!

**Pull request merged**
