### PR TITLE
Update Readme to reflect correct required ruby version

### PR DESCRIPTION
**Pull request by rturumella**
The Gemfile and README were not in sync.

### CODE REVIEW

**Comment by nickbarnwell** [comment]
Let's stop this from happening in the future and just make the README say "latest Ruby version as specified by `.ruby-version` :)

**Comment by mehulkar** [comment]
:+1: remove the note entirely.

**Comment by rturumella** [comment]
@nickbarnwell there you go!

**Comment by nickbarnwell** [comment]
:+1:, thanks Rohit!

**Pull request merged**
