### PR TITLE
attendance marking style changes

### PR DESCRIPTION
**Pull request by ankitshah811**

### CODE REVIEW

**Comment by mehulkar** [comment]
Oh wow, 38 commits for a +3 -5 diff. Mind if I fix this?

**Comment by mehulkar** [comment]
I take that back, when i pull down the master and attendance branches I get a larger diff. Not sure what's going on here.

**Comment by nickbarnwell** [comment]
I rebased attendance on top of master and `--force` pushed it so that history would be preserved, not thinking anyone would work on the branch further. Ankit did and did a `git pull` which produces that horrid merge commit, along with the botched stuff in 8abd354

**Comment by ankitshah811** [comment]
@nickbarnwell is there an easy way to clean up this PR without ruining everything?

**Comment by nickbarnwell** [comment]
No easy way to clean up without tons of `git`-fu.

**Pull request closed without merging**
